#!/bin/bash
MYIP=$(wget -qO- ipinfo.io/ip);
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
green='\e[0;32m'
NC='\e[0m'
c="\033[0;36m" #biruterang
g="\e[92;1m"
OR='\033[1;93m'
# ==========================================
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kytrx/regip/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/YSSHstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281215360549"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear 
echo -e " ${OR}  ┌───────────────────────────────┐$NC"
echo -e " ${OR}  │${NC}${g}.::.${NC} MENU BANDWIDTH MANAGER ${NC}${g}.::. $NC"
echo -e " ${OR}  └───────────────────────────────┘$NC"
echo -e "${OR}┌──────────────────────────────────────────┐\033[0m"
echo -e "${OR}│  ${g}1.${NC}${c} Monitor Bandwidth per Days"
echo -e "${OR}│  ${g}2.${NC}${c} Monitor Bandwidth per Month"
echo -e "${OR}│  ${g}3.${NC}${c} Live Bandwidth"
echo -e "${OR}│  ${g}4.${NC}${c} Back To Menu"
echo -e "${OR}└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1) 
vnstat -d
echo -e ""
read -n 1 -s -r -p "Enter To Back..."
bw
;;
2) 
vnstat -m
echo -e ""
read -n 1 -s -r -p "Enter To Back..."
bw
;;
3) 
vnstat -l
echo -e ""
read -n 1 -s -r -p "Enter To Back..."
bw
;;
4)
menu
;;
*)
exit
;;
esac
