#!/bin/bash
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kytrx/regip/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/YSSHstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281215360549"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
red='\e[1;31m'
green='\e[1;32m'
blue="\033[1;96m"
OR='\033[1;93m'
NC='\e[0m'
clear
echo -e "  ${OR}──────────────────────────────────────${NC}"
printf "\e[1;92m .::.\e[0m\e[1;77m  Set Limit IP SSH Account  \e[1;92m.::.\e[0m\n"
echo -e "  ${OR}──────────────────────────────────────${NC}"
echo "  USERNAME          EXP DATE          STATUS"
echo -e "  ${OR}──────────────────────────────────────${NC}"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
  printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "LOCKED"
else
  printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "UNLOCKED"
fi
fi
done < /etc/passwd
echo -e "  ${OR}──────────────────────────────────────${NC}"
read -rp " Input Username : " user
if [ -z $user ]; then
echo -e " You have no existing clients!"
sleep 2 ; m-sshws
else
rm -f /etc/kyt/limit/ssh/ip/${user}
read -p "Limit User (IP): " iplimit
echo ${iplimit} >> /etc/kyt/limit/ssh/ip/${user}
systemctl restart ws > /dev/null 2>&1
systemctl restart dropbear > /dev/null 2>&1
systemctl restart ssh > /dev/null 2>&1
clear
TEXT="
<code>───────────────────────────</code>
<code>     CHANGE LIMIT SSH OVPN</code>
<code>───────────────────────────</code>
<code>Username : $user</code>
<code>Limit Ip : $iplimit IP</code>
<code>───────────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo -e "  ${OR}───────────────────────────────────────${NC}"
printf "\e[1;92m   .::.\e[0m\e[1;77m  Succes Set Limit IP SSH  \e[1;92m.::.\e[0m\n"
echo -e "  ${OR}───────────────────────────────────────${NC}"
echo "   Username : $user"
echo "   Limit IP : $iplimit IP"
echo -e "  ${OR}───────────────────────────────────────${NC}"
echo -e ""
fi