#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author: YSSHstore
# //	Dscription: Xray Menu Management
# //	email: admin@yogz.com
# //  telegram: https://t.me/YSSHstore
# //====================================================
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
OR='\033[1;93m'
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kytrx/regip/main/ip"
CITY=$(cat /etc/xray/city)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
domain=$(cat /etc/xray/domain)
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e "\033[42m          YOGZZTUNNEL AUTOSCRIPT          ${NC}"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${Green}WhatsApp${NC} wa.me/6281215360549"
    echo -e "         \033[0;36mTelegram${NC} t.me/YSSHstore"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    exit
  fi
}
checking_sc
clear

echo -e "  ${OR}──────────────────────────────────────${NC}"
printf "\e[1;92m     .::.\e[0m\e[1;77m Trial SSH OVPN Account \e[1;92m.::.\e[0m\n"
echo -e "  ${OR}──────────────────────────────────────${NC}"
echo ""
read -p "  Expired (Minutes): " timer

user=trial$(tr </dev/urandom -dc X-Z0-9 | head -c4)
PASSWD=1
iplimit=2
useradd -e $(date -d "1 days" +"%Y-%m-%d") -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n" | passwd $user &>/dev/null
cat >/var/www/html/ssh-$user.txt <<END

---------------------
Format SSH OVPN Account
---------------------
Username         : $user
Password         : $PASSWD
---------------------
IP               : $ipsaya
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Location         : $CITY
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100, 7300, 7300
---------------------
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
---------------------
OpenVPN Link     : http://$domain:85
---------------------
Expired          : $exp

END

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${PASSWD} ${iplimit} ${timer}" >>/etc/ssh/.ssh.db
systemctl restart sshd
tmux new-session -d -s $user "trial trialssh $user $timer"
clear -x
echo -e "${OR}───────────────────────────${NC}"
echo -e "\e[92;1m     SSH OVPN Account     \E[0m"
echo -e "${OR}───────────────────────────${NC}"
echo -e "Username         : $user"
echo -e "Password         : $PASSWD"
echo -e "${OR}───────────────────────────${NC}"
echo -e "IP               : $ipsaya"
echo -e "Host             : $domain"
echo -e "Host Slowdns     : ${NS}"
echo -e "Port OpenSSH     : 443, 80, 22"
echo -e "Port UdpSSH      : 1-65535"
echo -e "Port DNS         : 443, 53 ,22 "
echo -e "Port Dropbear    : 443, 109"
echo -e "Port Dropbear WS : 443, 109"
echo -e "Port SSH WS      : 80, 8080"
echo -e "Port SSH SSL WS  : 443"
echo -e "Port SSL/TLS     : 443"
echo -e "Port OVPN WS SSL : 443"
echo -e "Port OVPN SSL    : 443"
echo -e "Port OVPN TCP    : 443, 1194"
echo -e "Port OVPN UDP    : 2200"
echo -e "Proxy Squid      : 3128"
echo -e "BadVPN UDP       : 7100, 7300, 7300"
echo -e "Pub Key          : ${PUB}"
echo -e "${OR}───────────────────────────${NC}"
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "${OR}───────────────────────────${NC}"
echo -e "OpenVPN Link     : https://$domain:81"
echo -e "${OR}───────────────────────────${NC}"
echo -e "Save Link Account: https://$domain:81/ssh-$user.txt"
echo -e "${OR}───────────────────────────${NC}"
echo -e "Expired On       : $timer Minutes"
echo -e ""