#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
OR='\033[1;93m'
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
IP=$(curl -sS ifconfig.me)
CITY=$(cat /etc/xray/city)
clear
NUMBER_OF_CLIENTS=$(grep -c -E "### " "/etc/ssh/.ssh.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
  echo -e "${OR}───────────────────────────\033[0m"
  echo -e "\e[1;97;101m   DETAIL SSH ACCOUNT          \E[0m"
  echo -e "${OR}───────────────────────────\033[0m"
                echo ""
                echo "You have no existing clients!"
                clear
                exit 1
        fi

  echo -e "${OR}───────────────────────────\033[0m"
  echo -e "\e[1;97;101m   DETAIL SSH ACCOUNT         \E[0m"
  echo -e "${OR}───────────────────────────\033[0m"
        echo "     No  Expired   User"
        grep -E "### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
user=$(grep -E "### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
domain=$(cat /etc/xray/domain)
Pass=$(grep "$Pass" /etc/ssh/.ssh.db | cut -b 21-56 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`

clear
echo ""
echo -e "${OR}───────────────────────────\033[0m"
echo -e "\e[92;1m     SSH OVPN Account     \E[0m"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» Username         : $user"
echo -e "» Password         : $Pass"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» IP               : ${IP}"
echo -e "» Host             : ${domain}"
echo -e "» Host Slowdns     : ${NS}"
echo -e "» Port OpenSSH     : 443, 80, 22"
echo -e "» Port DNS         : 53, 5300"
echo -e "» Port SSH UDP     : 1-65535"
echo -e "» Port Dropbear    : 443, 109"
echo -e "» Port SSH WS      : 80, 8080"
echo -e "» Port SSH SSL WS  : 443"
echo -e "» Port SSL/TLS     : 400-900"
echo -e "» Port OVPN WS SSL : 443"
echo -e "» Port OVPN SSL    : 443"
echo -e "» Port OVPN TCP    : 443, 1194"
echo -e "» Port OVPN UDP    : 2200"
echo -e "» BadVPN UDP       : 7100, 7300, 7300"
echo -e "» Pub Key          : ${PUB}"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» OpenVPN Download : https://$domain:81/"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» Save Link Account: https://$domain:81/ssh-$Login.txt"
echo -e "${OR}───────────────────────────\033[0m"
echo -e "» Expired          : $exp"
echo -e "${OR}───────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws